### PR TITLE
Implementation of edit frame component

### PR DESCRIPTION
**Pull request by mjarosch**
Updated the edit frame implementation from @erzr. I have updated it to work with the latest changes and added some additional functionality.

The purpose of this pull request is to request feedback while I work on Angular and Vue implementations.

## Description / Motivation

Implementation of an EditFrame component. Allows you to have an EditFrame component with web edit and field edit buttons.

## Testing Details

Manually, only locally.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### CODE REVIEW

**Comment by mjarosch** [comment]
Vue component is working, on to angular.

**Comment by mjarosch** [comment]
@art-alexeyenko or @ambrauer is there an equivalent for the sitecoreContext in angular? I am looking and I see the concept of context in the sample template, but nothing in the angular library itself. I need to know the route and pageediting mode for the editframe.

**Comment by mjarosch** [comment]
Angular implementation is in there. What needs to be cleaned up? What needs to be done for testing?

**Comment by art-alexeyenko** [comment]
Holy...wow!
Thanks a lot @mjarosch! And sorry I didn't get back to you on that question about context.

We'll be taking a closer look at this for sure. In the meantime, if you got time, and don't mind, could you add some unit tests?

**Comment by mjarosch** [comment]
@art-alexeyenko I have some unit tests in for the core and react pieces. I'll try and get some tests in for the vue and angular over xmas break here.

This is my first NextJS and Typescript project, so I would appreciate any feedback on better ways to do things.

**Comment by art-alexeyenko** [comment]
Hey @mjarosch ! Sorry for not getting back to you here - we finalized your implementation behind the scenes and posted the updated PR just now. Please feel free to take a look, any comments from you would be very appreciated.

**Comment by art-alexeyenko** [comment]
I'll close this PR since we merged the changes in https://github.com/Sitecore/jss/pull/1342 , but please feel free to add any comments you might have.

**Pull request closed without merging**
