### PR TITLE
[Docs] Migration guide - component structure section

### PR DESCRIPTION
**Pull request by anastasiya29**
Starting point for a migration guide. This adds a section for component structure

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [x] Documentation update (non-breaking change; modified files are limited to the `/docs` directory)

## Checklist:

- [ ] I have read the Contributing guide.
- [ ] My code follows the code style of this project.
- [ ] My code/comments/docs fully adhere to the Code of Conduct.
- [ ] My change is a code change and it requires an update to the documentation.
- [ ] My change is a documentation change and it requires an update to the navigation.

### CODE REVIEW

**Comment by nickwesselman** [comment]
We mention this generally in the 'differences' topic, do we want to include this content from the get-go or save it until we have a (verified) procedure for migrating?

**Review by AncaIO — APPROVED** [review]

**Comment by AncaIO** [comment]
> We mention this generally in the 'differences' topic, do we want to include this content from the get-go or save it until we have a (verified) procedure for migrating?

As @anastasiya29  mentions in the description, it's a start for a migration guide. I don't know if we have the time to do more on it until the deadline. 

I wonder how much of https://nextjs.org/docs/migrating/from-create-react-app applies, or rather what JSS specific tasks one would need to perform to switch to Next.js. 

Perhaps a reasonable solution now is to not merge this for now and give it `HIGH` prior right after release?

**Comment by anastasiya29** [comment]
Another option - merge it, but exclude from navigation until it's complete?

**Comment by nickwesselman** [comment]
Merged / unlinked works for me

**Pull request merged**
