### PR TITLE
[NextJS] Add prefetchLinks parameter to RichText component

### PR DESCRIPTION
**Pull request by pschofield**
- [x] This PR follows the [Contribution Guide](https://github.com/Sitecore/jss/blob/dev/CONTRIBUTING.md)
- [ ] Changelog updated

## Description / Motivation
When the RichText component contains a large number of internal links, the number of network calls to prefetch these links can be quite large. It would be ideal to have the ability to disable the prefetch step, similar to how the next/link component allows the prefetch to be enabled/disabled. The existing default behaviour (prefetch is performed) would be maintained.

## Testing Details
- [x] Unit Test Added
- [x] Manual Test/Other (Please elaborate)
Manual testing involved applying the proposed change to a local dev instance of Sitecore 10.3 and verifying that link prefetching didn't occur when prefetchLinks was set to false. Also observed that prefetching occurs when prefetchLinks is either not explicitly set or set to true.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
This PR addresses feature request #1516:
https://github.com/Sitecore/jss/discussions/1516

### CODE REVIEW

**Comment by sc-addypathania** [comment]
@pschofield Thankyou again for your contribution.
I think this is a great idea and would allow users or developers to have more control over the trade-off between performance and resource usage.

Please update the changelog so I can merge the PR. :)

**Review by sc-addypathania — APPROVED** [review]
@pschofield Thankyou for your contribution.
I think this is a great idea and would allow users or developers to have more control over the trade-off between performance and resource usage.

Approved 👍🏼 
Please update the changelog so I can merge the PR later :)

**Comment by pschofield** [comment]
> @pschofield Thankyou for your contribution. I think this is a great idea and would allow users or developers to have more control over the trade-off between performance and resource usage.
> 
> Approved 👍🏼 Please update the changelog so I can merge the PR later :)

Hi @sc-addypathania
thanks, I've updated the changelog

**Comment by pschofield** [comment]
And fixed merge conflict

**Pull request merged**
