### PR TITLE
Fixed docs typos

### PR DESCRIPTION
**Pull request by alan-null**

### CODE REVIEW

**Comment by aweber1** [comment]
Thanks for the contribution! In order to ease the process for publishing documentation changes in between code/feature releases, we recently implemented new guidelines for documentation contributions:
https://github.com/Sitecore/jss/blob/dev/CONTRIBUTING.md#documentation-contributions

Basically, we ask that you base your changes off the `master` branch instead of `dev`.

**Comment by alan-null** [comment]
Hey @aweber1 
This is what I did
image
`master`
image
`feature/typos`
image

**Comment by aweber1** [comment]
Awesome! Can you change the PR to target the master branch instead of dev?

**Comment by alan-null** [comment]
Sure, done.

**Comment by aweber1** [comment]
Changes have been published, thanks again!

**Pull request merged**
