### PR TITLE
Fixes angular scaffolding

### PR DESCRIPTION
**Pull request by kamsar**
Ref #90

Schematics have an issue where depending on the version of schematics in use there are different errors when one attempts to compose a scaffold of multiple template roots - in this case, a template for the manifest and another for the component.

With schematics 0.6 (angular 6) this results in an undefined entries. With schematics 7, it results in an infinite loop.

This commit works around that by not rebasing the manifest template and switching the manifest template to have a full path to the file. Doing this removes the ability to variableize the `manifestPath` but it does allow the scaffold to actually work. This also updates schematics to refer to schematics for angular 7+, which shipped with GA.

## Motivation

Scaffolding in Angular, without `--lazyload`, is currently broken.

## How Has This Been Tested?

Ran scaffolding lazy and not lazy against the angular sample app in the monorepo.

## Types of changes

- [X] Bug fix (non-breaking change which fixes an issue)
- [X] Breaking change (fix or feature that would cause existing functionality to change)

### CODE REVIEW

**Comment by kamsar** [comment]
All things are possible with Angular :trollface:

**Comment by kamsar** [comment]
@spike1292 does this seem reasonable to you? Not going to get in your way?

**Comment by spike1292** [comment]
> @spike1292 does this seem reasonable to you? Not going to get in your way?

We store the definitions next to the component, so this is a breaking change for use. This can be solved by moving the manifest manually.

The scaffold is now broken. So choosing between not working and a manual step. I prefer the manual step😉

**Comment by kamsar** [comment]
@spike1292 as a possible workaround you could scaffold with `--noManifest` and then scaffold that on the side with a different script, if you wanted to remove the manual step. React/Vue's scaffold script has stealable code.

**Pull request merged**
