### PR TITLE
Upgrade node to LTS

### PR DESCRIPTION
**Pull request by sc-addypathania**
Upgrade nodejs version to LTS.
- [x] This PR follows the [Contribution Guide](https://github.com/Sitecore/jss/blob/dev/CONTRIBUTING.md)

## Testing Details

- [ ] Unit Test Added
- [ ] Manual Test/Other (Please elaborate)

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### CODE REVIEW

**Comment by illiakovalenko** [comment]
@sc-addypathania Did you install sample apps manually, installed Node.js 18, and checked that it's still working? I remember we had some issues using Node.js 18

**Comment by sc-addypathania** [comment]
> @sc-addypathania Did you install sample apps manually, installed Node.js 18, and checked that it's still working? I remember we had some issues using Node.js 18

@illiakovalenko Yes I installed Nodejs 18 and tested it by installing nextjs without any issues. I can test others as well. Do you remember where you faced the issue?

**Comment by illiakovalenko** [comment]
@sc-addypathania No, can't recall. Just need to verify for rest

**Comment by sc-addypathania** [comment]
@illiakovalenko I have verified scaffolding and deploying all sample apps. I didn't stumble upon any issues. 
We should have a QA task for this to cover the remaining edge cases.

**Pull request merged**
