### PR TITLE
ember support!

### PR DESCRIPTION
**Pull request by alexshyba**
## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] I have read the Contributing guide.
- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.

### CODE REVIEW

**Comment by aweber1** [comment]
Thanks for the contribution, but closing in favor of Knockout.

**Comment by cdvillard** [comment]
See, I came here thinking this might actually be a thing, but now I'm confused. Is this officially closed, or is Ember being harped on here? I don't get it.

**Comment by kamsar** [comment]
This was an inside joke issue to test a workflow. It shouldn't be treated as a possible roadmap ;)

Nothing against Ember; while it's mature it's not as popular as the other frameworks we already support.

**Comment by cdvillard** [comment]
Hahah, okay. Still, might take that good first issue tag on as a challenge.
:P

**Pull request closed without merging**
