### PR TITLE
[Nextjs][SDK] RichText component not forwarding query params

### PR DESCRIPTION
**Pull request by sc-addypathania**
Fix to forward query params from the RichText component.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### CODE REVIEW

**Review by ambrauer — APPROVED** [review]
Looks good to me!

**Comment by thaiphan** [comment]
Thanks!

**Comment by pzi** [comment]
Any chance for a patch of v20 @ambrauer / @sc-addypathania ?

**Comment by sc-addypathania** [comment]
@pzi We will soon be doing a minor release. This fix would be a part of it.

**Comment by pzi** [comment]
Glorious, thank you @sc-addypathania

**Pull request merged**
