### PR TITLE
Fix memory leak for sclink scimage

### PR DESCRIPTION
**Pull request by zwang-rocket**
We noticed memory leak with scImage and scLink. found we do not destory the views.

PLEASE backport to 16.0.x if possible. Thanks

- [x] This PR follows the [Contribution Guide](https://github.com/Sitecore/jss/blob/dev/CONTRIBUTING.md)

## Testing Details

- [ ] Unit Test Added
- [ ] Manual Test/Other (Please elaborate)

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### CODE REVIEW

**Comment by art-alexeyenko** [comment]
@zwang-rocket thank you for registering the PR!
Do you have a sample scenario to illustrate the issue, so we can add it to our backlog and test the fix?

**Comment by zwang-rocket** [comment]
> @zwang-rocket thank you for registering the PR! Do you have a sample scenario to illustrate the issue, so we can add it to our backlog and test the fix?
Thanks @art-alexeyenko, Here is a grafana screen shot  of memory usuage for our service with SSR
green line is memory usage with this fix.
yellow line is memory usage without this fix with same load. As you can see the yellow line just goes up and eventually got killed OOM.

image

**Comment by art-alexeyenko** [comment]
@zwang-rocket so just adding a bunch of images and requesting a page multiple times should be enough, thank you!

**Comment by illiakovalenko** [comment]
@zwang-rocket @art-alexeyenko I closed this PR since related PR includes these changes and is merged #1435

**Pull request closed without merging**
