### PR TITLE
Allow using SitecoreContext with a hook

### PR DESCRIPTION
**Pull request by jantimon**
## Description

On February 16, 2019, React `16.8` was released by facebook and added `hooks` to make functional components more powerfull.

This pull request allows using the `SitecoreContext` with way less effort than the current High Order Component approach `withSitecoreContext`:

```ts
const EditMode = () => {
   const {pageEditing} = useSitecoreContext();
   return <span>Edit Mode is {pageEditing ? 'active' : 'inactive'}</span>
}
```

## How Has This Been Tested?

This feature has **not** been tested.   
If you think this would be a good addition I will go on with testing.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentation update (non-breaking change; modified files are limited to the `/docs` directory)

## Checklist:

- [ ] I have read the Contributing guide.
- [ ] My code follows the code style of this project.
- [ ] My code/comments/docs fully adhere to the Code of Conduct.
- [ ] My change is a code change and it requires an update to the documentation.
- [ ] My change is a documentation change and it requires an update to the navigation.

### CODE REVIEW

**Comment by kamsar** [comment]
Presumably adding hooks would require dropping support for React < 16.8. IMO that is worth doing but it's @AdamNaj who would make that decision. It could also be done in a separate hooks package perhaps to avoid that necessity.

Hooks make React really, really nice and IMO it's time JSS got them for context and also the placeholder transforms.

**Comment by jantimon** [comment]
Cool thanks for your feedback 👍

Actually this change is not breaking backwards compatibility.
`useSitecoreContext` would only cause an error `React.useContext is not a function` for old versions once it is called.  

As long as this new hook is not being used, everything will work just as it did before.  

But you are right a next step might be to use it internally and then it would definitely require react 16.8.

**Comment by sc-illiakovalenko** [comment]
@jantimon Thank you, I merge it in future JSS 16 release

**Comment by sc-illiakovalenko** [comment]
@jantimon Added new useSitecoreContext hook in #508

**Comment by jantimon** [comment]
Thanks @sc-illiakovalenko 👍

**Pull request closed without merging**
