### PR TITLE
Updated en,md

### PR DESCRIPTION
**Pull request by bala-one**
Added a Note: When using SXA with JSS ensure the site and app node are commented in the Sitecore `.config` file in `/sitecore/config`. Since this will be handled by SXA Site manager. We faced this issue and took two weeks with Sitecore to figure out the issue. https://sitecore.stackexchange.com/questions/29221/using-page-designs-or-partial-designs-in-sxa-jss-site

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentation update (non-breaking change; modified files are limited to the `/docs` directory)

### CODE REVIEW

**Comment by CobyPear** [comment]
Thank you for this PR. I believe this information is covered in the appropriate docs [here](https://doc.sitecore.com/en/developers/sxa/101/sitecore-experience-accelerator/import-a-jss-app-into-your-jss-site.html). @ancaemcken what are your thoughts?

**Comment by ancaemcken** [comment]
> Thank you for this PR. I believe this information is covered in the appropriate docs [here](https://doc.sitecore.com/en/developers/sxa/101/sitecore-experience-accelerator/import-a-jss-app-into-your-jss-site.html). @ancaemcken what are your thoughts?

@CobyPear I'll pass along the information to the owner of the SXA docs. @bala-one  thanks for spotting this.

**Comment by ancaemcken** [comment]
@bala-one @CobyPear The SXA folk are looking to confirm/test the solution on their end. We will update the relevant documentation (JSS and SXA).

**Comment by ancaemcken** [comment]
@CobyPear I think we can close / discard this PR because of having moved the docs out of the repo and the fact that it is documented in the SXA docs.

**Pull request closed without merging**
